### PR TITLE
Fable.Elmish TimePicker component

### PR DESCRIPTION
**Pull request by EdouardM**
Hello Maxime, 

I implemented the time picker component here. I was heavily inspired by a Vue implementation available here : https://github.com/phoenixwong/vue2-timepicker/blob/master/src/vue-timepicker.vue

Please feel free to make comments on this solution.

### CODE REVIEW

**Comment by EdouardM** [comment]
Hello Maxime, 

The AppVeyor build failed with a error message mentionning Yarn Helper from FAKE. The solution submitted was building fine on my computer. 

Do I have something to change on my side or is it related to AppVeyor? 

Regards;
Edouard

**Comment by MangelMaxime** [comment]
This is a problem on how app veyor configure their env and fake.

I will fix the fake script later. No worries on this side 😊

**Comment by MangelMaxime** [comment]
Also, I don't forget you PR, it's just I have started to work on the next version of Fulma and so want to include this PR in it directly with the new architecture.

**Comment by MangelMaxime** [comment]
I'm going to close this PR as Fulma packages will receive a revamp.

**Pull request closed without merging**
