### PR TITLE
Font Awesome 5

### PR DESCRIPTION
**Pull request by selketjah**
#151 

WIP

### CODE REVIEW

**Comment by selketjah** [comment]
So, I checked out the current 4.7 and I don't think we can use the same way for Font Awesome 5:
you have a "style" now and some, but not all, icons have multiple styles.
So you define the icon and the style of the icon now.

image

needed html output:
``` html
<i class="far fa-address-book"></i>
<i class="fas fa-address-book"></i>
```

Right now I just made 3 DU's:
* Solid (fas)
* Regular (far)
* Brands (fab)

But this reminds me a bit of the "Width" property of the column, so maybe this isn't the best way forward.
Any input on design welcome

**Comment by MangelMaxime** [comment]
Hum the problem is that not all the icons have the 3 states valid.

For example, `fa-apple` only support `fab` when `fa-address-book` supports `fas`, `far` and `fal`.

I think that if an icon is from a Brand then it will support only the `fab` style. When others icons probably support all 3 styles.

I think we should provide an API like that:

```fs
Fa5.I.Apple // generates `fab fa-apple`

Fa5.I.AddressBook.Regular // generates `far fa-address-book`
Fa5.I.AddressBook.Solid // generates `fas fa-address-book`
Fa5.I.AddressBook.Light // generates `fal fa-address-book`
```

For the brands no need to specify `.Brand` at the end of it because it's the only valid case. 

Where for the others icons, we need to specify the supported type. We can't do something like:

```fs
Icon.faIcon [ ]
    [ Fa.I.AddressBook
      Fa.I.IsSolid ]
```

because we can't make

```fs
Icon.faIcon [ ]
    [ Fa.I.Apple
      Fa.I.IsSolid ]
```

an impossible state.

**Comment by selketjah** [comment]
Do you only want to offer the available states if they are free icons?
Because that would hugely impact the decision.

Basically all icons have a `solid`, `regular` or `light`, but:
- light is only available in the pro
- regular is often only available in the pro

And besides that you have the Brand icons, which don't have a state.

**Comment by MangelMaxime** [comment]
I want to support free and pro icons. 

Because I don't think we can offer a nice API for separating them.

**Comment by selketjah** [comment]
Damn, made the wrong javascript then :( 

So why would this not be a good idea if we offer all states?

``` fsharp
Icon.faIcon [ ] [ Fa.brand Fa.B.Amazon ] // for brands
Icon.faIcon [ ] [ Fa.icon(Fa.I.Accessible, Fa.State.IsSolid) ] // for state icons
```

**Comment by MangelMaxime** [comment]
Then for `Fa.brand` users need to understand this additional layers but I am ok with your proposition as long as all the icons can support all 3 states.

If one of the icon does not support one of the 3 states then we would need to go with my solution to make it impossible to write an invalid code.

**Comment by selketjah** [comment]
@MangelMaxime Do you want to support these new features?

* https://fontawesome.com/how-to-use/on-the-web/styling/layering
* https://fontawesome.com/how-to-use/on-the-web/styling/masking
* https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms

**Comment by selketjah** [comment]
@MangelMaxime I think this is ready. I'm not 100% happy with the FontAwesome and FontAwesome5 modules approach, suggestions more than welcome. And of course if you have any other feedback...

image

**Comment by MangelMaxime** [comment]
I am planning to work on Fulma this week-end, accept PR and split the packages to make it easier to work with, maintains.

By splitting the package I want to explode `Fulma.Extension` into one package per extension so I can know exactly which version of the lib support which version of the extension.

And I have the idea to do the same for `FontAwesome` and remove it from `Fulma`. So, like that others people can also use `FontAwesome` bindings and also I can do:

- v1.x supports FontAwesome4
- v2.x supports FontAwesome5

And so we would have `Fulma.FontAwesome4` and `Fulma.FontAwesome5` packages.

So yes, Fulma will needs more package to be installed just as in JavaScript but make it easier to know which version are supported.

**Comment by MangelMaxime** [comment]
I will merge the PR during the week-end and work from here :)

**Pull request merged**
