### PR TITLE
Add slider

### PR DESCRIPTION
**Pull request by evilz**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
This is great :clap: :clap: :clap:

**Comment by MangelMaxime** [comment]
@evilz I updated your PR can you please review the changes.

In summary:
- I added Min, Max, Value, DefaultValue as it's important to control the slider behavior in Elmish. In general, we never late the browser do his default behavior as it's leads to side effects.
- I fixed the docs view, made the space works and fixed typo.
- Allow, users to set their slider to be vertical

**Comment by MangelMaxime** [comment]
Ah yes, and if you plan to use this component in one of your project be careful the display is really not great under Chromium/Chrome (Linux).

image

**Comment by evilz** [comment]
In fact Wikiki is working on it and broke something on css. It's look the same in Windows too. 
I saw that he's working on a vertical slider. 
So we will need to update npm soon and add a new property.

Nice clean thank

**Comment by MangelMaxime** [comment]
In fact, I already added the vertical property. But yes upgrading the version is easier now that we have the basics :) Thanks again

**Comment by MangelMaxime** [comment]
Thanks you for the PR.

I have rebase this PR to the latest master version. I will clean the code on master from now.

**Pull request merged**
