### PR TITLE
Added Quickview component

### PR DESCRIPTION
**Pull request by AkosLukacs**
Current usage looks like this:

```F#
let qView isActive closeDisplay =
    Quickview.quickview [ Quickview.IsActive isActive ]
        [ Quickview.header [ ]
            [ Quickview.title [ ] [ str "Testing..." ]
              Delete.delete [ Delete.OnClick closeDisplay ] [ ] ]
          Quickview.body [ ]
            [ str "The body" ]
          Quickview.footer [ ]
            [ str "legs" ] ]

//...
// in the view (the two messages just set/clear a bool):
  qView model.isQuickviewActive (fun _ -> HideQuickView |> dispatch)
  Button.button [ Button.OnClick (fun _ -> ShowQuickView |> dispatch)] [ str "Show quickview" ]
```

+ 1 more typo in Tile :)

### CODE REVIEW

**Comment by MangelMaxime** [comment]
I take a quick look at the code. It's looks fine.

Would you be able to add the documentation page too ? Do you need help ?

**Comment by AkosLukacs** [comment]
Will give it a try, and ping you, if I'm stuck.

2018. márc. 1. 4:32 du. ezt írta ("Maxime Mangel" <notifications@github.com

**Comment by AkosLukacs** [comment]
Added docs with a demo, and fixed some links.

**Comment by MangelMaxime** [comment]
Thank you for the various fixes :)

**Comment by MangelMaxime** [comment]
Released under Fulma.Extensions.1.0.0-beta-011

**Pull request merged**
