### PR TITLE
Rework the user experience and upgrade Bulma support to latest

### PR DESCRIPTION
**Pull request by MangelMaxime**
Related issues: #73 #92 #47 #91 #87 

*The upgrade to latest Bulma version isn't yet included in this PR.*

Changes introduce to improve UX:

### Remove small helpers

Remove all the small helpers, which was just wrapping the DUs definitions.

Example:

```fs
// Before
Button.button_a [ Button.isOutlined ] [ str "Outlined" ] 

// Now
Button.button [ Button.IsOutlined ] [ str "Outlined" ] 
```

This as the benefit of making all the "properties" using `PascalCase` identifiers, where "render functions" are in `camelCase`.

By removing, the small helpers, we now don't have access to helpers like `Button.isDanger`, we now expose the `IColor` and `ISize` type to the user.

Example:

```fs
// Before
open Fulma.Elements
Button.button_a [ Button.isSuccess
                  Button.isSmall ] 
    [ str "A button" ] 

// Now
open Fulma
open Fulma.Elements
Button.button [ Button.Color IsSuccess
                Button.Size IsSmall ] 
    [ str "A button" ] 
```

This is a little bit more verbose for the users, but improve code quality in the library. This also, have the benefit of sharing the `Size`, `Color` parser and allow users to support this properties in their components, in 4 lines for each versus 8-14 before.

#### Additional effect

Removing the small helpers also, means that options of render function using `GenericOption` are no more available inside the component module.

```fs
// Before
open Fulma.Elements
Modal.background [ Modal.Background.props [ OnClick (fun _ -> dispatch ToggleCardModal) ] ] [ ] 

// Now
open Fulma
open Fulma.Elements

Modal.background [ Props [ OnClick (fun _ -> dispatch ToggleBasicModal) ] ] [ ]
```

The compiler, will of course help you understand this. In general, you will probably always `open Fulma` need to open in your files because, this will expose common / generic properties to you (`Props`, `CustomClass`, `Color`, `Size`, `Modifiers`, etc.)

### Remove `underscore` functions

In previous version of Fulma, we was trying to map 100% of Bulma usage and so I introduce the `underscore` helpers like `Button.Button_a`, `Button.Button_input`, `Field.field_div`, `Field.field_p`. I am removing this helpers in two ways.

If there is no difference in term of "components", browser experience between two version of a component then we now support only one case. For example, between `Field.field_div` and `Field.field_p` their, is no visual change. Same of the button element. So we now only have `Button.button` and `Field.field`.

However, for some elements if you use a `div` or `a` as the root element it's give a different result. It's the case for the `Navbar.Item` for example where, you get the anchor feedback or no. In this case, we have this changes:

```fs
// Before
Navbar.brand_div [ ]
            [ Navbar.item_a [ Navbar.Item.props [ Href "#" ] ]
                [ img [ Style [ Width "2.5em" ] // Force svg display
                        Src "/assets/logo_transparent.svg" ] ] ]
// Now
Navbar.Brand.div [ ]
            [ Navbar.Item.a [ Navbar.Item.Props [ Href "#" ] ]
                [ img [ Style [ Width "2.5em" ] // Force svg display
                        Src "/assets/logo_transparent.svg" ] ] ]
```

To summarize this points, Fulma is trying to think in term of "Bulma elements" and not DOM elements.

### Avoid "computation lists" in user code

Even if the "computation list" is a really powerful feature, it's make the code harder to read. And thanks to React 16 we now have a lot of helpers to build the children part of the React DSL.

```fs
//Before
PageLoader.pageLoader [ yield PageLoader.Types.Color model.Color 
                       if model.IsLoading then 
                        yield PageLoader.isActive ] [ ]
// Now
PageLoader.pageLoader [ PageLoader.Color model.Color
                        PageLoader.Active model.IsLoading ] [ ]
``` 

This is the same for the `IsDisabled`, `IsLoading` properties etc. If you see a place where you we need to use comprehension list for the state of an element then, we need to fix it in Fulma. 

### Uniform way to generate `classes`

`Helpers.classes` is now always used to generate the classes for an element. Before, we was having 2 different helpers and sometimes doing it manually. It's now all the time the same way.

### Remove `BulmaClasses.fs`

Remove `BulmaClasses.fs` usage. We now include directly in the element file.

Exampe `Button.fs`:

```fs
namespace Fulma.Elements

open Fulma
open Fable.Import.React
open Fable.Helpers.React
open Fable.Helpers.React.Props

[<RequireQualifiedAccess>]
module Button =

    module Classes =
        let [<Literal>] Container = "button"
        module State =
              let [<Literal>] IsHovered = "is-hovered"
              let [<Literal>] IsFocused = "is-focus"
              let [<Literal>] IsActive = "is-active"
              let [<Literal>] IsLoading = "is-loading"
              let [<Literal>] IsStatic = "is-static"
        module Styles =
            let [<Literal>] IsFullwidth = "is-fullwidth"
            let [<Literal>] IsLink = "is-link"
            let [<Literal>] IsOutlined = "is-outlined"
            let [<Literal>] IsInverted = "is-inverted"
```

This should improve a little the compilation time and also reduce the JS generated. Because `Classes` module only contains `[<Literal>]` values, it's erased from the output. Before, `BulmaClasses.fs` was having some records inside the modules and so was including in the ouput.

*BulmaClasses.fs* isn't 100% removed yet, I need to work on the Modifiers classes.

### Split nested modules into several files

@alfonsogarciacaro mentioned that Tree Shaking don't work well with nested modules containing codes. So this is what motived to remove the `BulmaClasses.fs` file and also I splitted all the `Form.fs` file into 10 files now. Because, we probably don't use all the Form elements inside the app forms.

We still have nested modules into others files, because otherwise the maintenance would be too hight. Another reason, is also if you use the `Card` components, there is a lot of chance that you use the `Header` modules too etc. And they are much smaller than the previous `Form` modules.

### Only expose needed Api

I also, include a bunch of `internal` on some types or function to expose only what is need to the user.

-------

Questions for @alfonsogarciacaro , I think we could reduce the bundle size by using `[<Pojo>]` almost everywhere what do you think ?

Also, I think we should use **enumeration** for `Column.ISize`, `Column.IScreen` what's your opinion ?

In this PR, I listed all the major changed done in term of UX and architecture. I didn't mention every changed, made in each DUs case. I will probably do it for the migration guide but not much interest IMO in this PR.

If you want to see the API changes, you can see them in the diff view of this PR.

I also, didn't updated the source code shown on the docs site, because we can still change the Api etc. I will do it before merging this PR.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Awesome @MangelMaxime, great work! 🥇 💃 🥇 I agree 100% with the changes and the motivations, it may be a bit of pain to update some apps, but it shouldn't be too hard with the guidance and anyways it's much better to do earlier rather than later :)

About whether using `Pojo` would reduce the bundle size we could measure it, but I guess so. Using enumerations will definitely help because they become just integers in generated JS.

**Comment by MangelMaxime** [comment]
Thanks for the feedback. Because, Fulma docs is using all the modules of Fulma, Fulma Extension, and Fulma Calendar, I will try to add the `<Pojo>]` attributes and see how much this remove. And same for the enumerations, I think I should be able to transform the common properties (Color, Size) to enum too.

**Comment by alfonsogarciacaro** [comment]
Cool. Just remember enumerations force you to qualify the case so you need to write: `Color.IsSuccess`, etc.

**Comment by MangelMaxime** [comment]
Oh... I was thinking to force fully qualify this properties too but not sure if people will like that.
We try to just use [<Pojo>] instead, this should already reduce the output size.

Thanks for pointing that out :)

**Comment by MangelMaxime** [comment]
*For references:*

We are not going to include additional attributes to reduce the bundle size. This optimization is planned to be added by Fable 2.0, by default.

**Comment by kunjee17** [comment]
@MangelMaxime thanks man for update. If any help required for testing new things then let me know.

**Comment by MangelMaxime** [comment]
This commit https://github.com/MangelMaxime/Fulma/pull/93/commits/136cf432b19cfb5d665723797778a0050b863921 is the start of a long series... And it's your fault @alfonsogarciacaro you put this idea in my head 😈

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Are you generating all these comments (semi)automatically or just by hand? Sorry, I mean comments in places where the API could be confusing! 😅 If it's too much work, please tell me and we can try to think of a way to automate the comment generation.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro It's just that like that people won't be surprised by which element generate.

And it's more or less copy/paste :D when viewing a film :p

To be fair, we have almost everything covered now.

**Pull request merged**
